from datetime import datetime, timezone


SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
}


def _severity_badge(severity: str) -> str:
    emoji = SEVERITY_EMOJI.get(severity.upper(), "⚪")
    return f"{emoji} {severity.upper()}"


def _remediation_links(references: list[dict]) -> list[str]:
    priority_tags = {"Patch", "Vendor Advisory", "Mitigation", "Third Party Advisory"}
    priority, others = [], []
    for ref in references:
        tags = set(ref.get("tags", []))
        if tags & priority_tags:
            label = ", ".join(sorted(tags & priority_tags))
            priority.append(f"- [{label}]({ref['url']})")
        else:
            others.append(f"- {ref['url']}")
    lines = priority + others[:3]  # cap generic refs at 3
    return lines if lines else ["- No patch references available yet — monitor the NVD entry for updates."]


def format_cve_section(cve: dict) -> str:
    score = cve["score"]
    severity = _severity_badge(cve["severity"])
    affected = cve["affected"]
    cwes = cve["cwes"]
    iocs = cve["iocs"]
    refs = _remediation_links(cve["references"])

    lines = [
        f"## {cve['id']} | CVSS {score} {severity}",
        "",
        f"**NVD:** {cve['nvd_url']}",
    ]

    if affected:
        lines.append(f"**Affected:** {', '.join(affected)}")
    if cwes:
        lines.append(f"**Weakness:** {', '.join(cwes)}")

    lines += [
        "",
        "### Situation",
        cve["description"],
        "",
        "### Potential IOCs",
        *[f"- {ioc}" for ioc in iocs],
        "",
        "### Remediation",
        *refs,
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def format_issue(cves: list[dict], date: str | None = None) -> tuple[str, str]:
    """Return (title, body) for the GitHub Issue."""
    if date is None:
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    critical = [c for c in cves if c["severity"].upper() == "CRITICAL"]
    high = [c for c in cves if c["severity"].upper() == "HIGH"]

    title = f"Daily CVE Report — {date} ({len(cves)} CVEs, {len(critical)} critical)"

    body_lines = [
        f"# Daily CVE Report — {date}",
        "",
        f"**{len(cves)}** CVEs published in the last 24 hours with CVSS ≥ 7.0",
        f"- 🔴 Critical (9.0–10.0): **{len(critical)}**",
        f"- 🟠 High (7.0–8.9): **{len(high)}**",
        "",
        "> *IOCs listed are potential indicators based on vulnerability class — "
        "treat as a starting point for threat hunting, not confirmed detections.*",
        "",
        "---",
        "",
    ]

    if not cves:
        body_lines.append("No CVEs with CVSS ≥ 7.0 were published in the last 24 hours.")
    else:
        for cve in cves:
            body_lines.append(format_cve_section(cve))

    body_lines += [
        "---",
        f"*Generated by [daily-cves](https://github.com/wj-tech/daily-cves) · "
        f"Source: [NVD](https://nvd.nist.gov)*",
    ]

    return title, "\n".join(body_lines)
